--- drivers/misc/Makefile
+++ drivers/misc/Makefile
@@ -68,3 +68,4 @@ obj-$(CONFIG_TMR_INJECT)	+= xilinx_tmr_inject.o
 obj-$(CONFIG_TPS6594_ESM)	+= tps6594-esm.o
 obj-$(CONFIG_TPS6594_PFSM)	+= tps6594-pfsm.o
 obj-$(CONFIG_CIX_SENSORHUB)		+= cix/sensor/core/
+obj-$(CONFIG_ARMCHINA_NPU)		+= cix/armchina-npu/
