ccflags-y += -I$(srctree)/drivers/misc/cix/sensor/core
ccflags-y += -I$(srctree)/drivers/misc/cix/sensor/scp/include

obj-$(CONFIG_CIX_KERNEL_SENSORHUB) += cix_sensorhub.o
cix_sensorhub-objs += cix_sensorhub_main.o sensor_list.o sensorhub_ipi.o
